name: Deploy CDKTF to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install cdktf-cli
        run: npm install -g cdktf-cli

      - name: Install project dependencies
        working-directory: ./GCP-CDKTF-Setup
        run: npm install

      - name: Generate CDK constructs
        working-directory: ./GCP-CDKTF-Setup
        run: cdktf get

      - name: Synthesize CDK
        working-directory: ./GCP-CDKTF-Setup
        run: cdktf synth

      - name: Deploy to GCP
        working-directory: ./GCP-CDKTF-Setup
        run: cdktf deploy --auto-approve
