name: GCP CDKTF Infrastructure Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Infrastructure to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm install

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli 

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5 # You can specify the version you want

      - name: Decode and Write GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ${{ github.workspace }}/gcp-key.json

      - name: Export Credential Path
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Verify GCP Authentication
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud info

      - name: Initialize CDKTF
        run: cdktf get

      - name: Synthesize Terraform Configuration
        run: cdktf synth

      - name: Deploy Infrastructure
        run: cdktf deploy --auto-approve

      - name: Deployment Successful
        run: echo "Infrastructure deployed successfully!!!"

  destroy:
    name: Destroy Infrastructure (Manual Trigger)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install NPM dependencies
        run: npm install

      - name: Install CDKTF CLI
        run: npm install -g cdktf-cli 

      - name: Install Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5 # Match the deploy version

      - name: Decode and Write GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > ${{ github.workspace }}/gcp-key.json

      - name: Export Credential Path
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV

      - name: Verify GCP Authentication
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud info

      - name: Initialize CDKTF
        run: cdktf get

      - name: Destroy Infrastructure
        run: cdktf destroy --auto-approve

      - name: Destroy Successful
        run: echo "Infrastructure destroyed successfully!!!"
